/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package unibaveopencode.gui.panel.components.buttons;

/**
 *
 * @author Stéfani
 */
public class JPBotaoImprimirQrCode extends javax.swing.JPanel {

    /**
     * Creates new form JPbotaoGerarQrCode
     */
    public JPBotaoImprimirQrCode() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jbImprimir = new javax.swing.JButton();
        jbFechar = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jbImprimir.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jbImprimir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/unibaveopencode/resource/image/Botao_imprimir_icone.png"))); // NOI18N
        jbImprimir.setText("Imprimir");
        jbImprimir.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jbImprimir.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        add(jbImprimir, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 120, 40));

        jbFechar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jbFechar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/unibaveopencode/resource/image/Botao_sair_icone.png"))); // NOI18N
        jbFechar.setText("Fechar");
        jbFechar.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jbFechar.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        add(jbFechar, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 10, 110, 40));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton jbFechar;
    public javax.swing.JButton jbImprimir;
    // End of variables declaration//GEN-END:variables
}
