/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package unibaveopencode.gui.iframe.screens;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.persistence.EntityManager;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;
import unibaveopencode.gui.iframe.search.JIFConsultaAutor;
import unibaveopencode.gui.panel.components.buttons.JPBotaoCadastro;
import unibaveopencode.gui.principal.JFPrincipal;
import unibaveopencode.util.Messages;
import unibaveopencode.model.vo.AutorVO;
import unibaveopencode.util.WindowUtil;

/**
 *
 * @author Stéfani
 */
public class JIFAutor extends javax.swing.JInternalFrame {
    private JFPrincipal principal;

    /**
     * Creates new form JIFAutor
     * @param principal
     */
    
    public JIFAutor(JFPrincipal principal) {
        initComponents();
        this.principal = principal;
        initBotoes();
    }

    private void initBotoes() {
        JPBotaoCadastro botoes = jPCadastroAutor.jPBotaoCadastro;
        botoes.jbSalvar.addActionListener(new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent ae) {
                EntityManagerFactory emf = null;
                EntityManager em = null;

                try {
                    emf = Persistence.createEntityManagerFactory("uocPU");
                    em = emf.createEntityManager();
                    em.getTransaction().begin();
                    AutorVO autor = new AutorVO();
                    autor.setCodAutor("".equals(jPCadastroAutor.jtfCodigo.getText()) ? null : Integer.parseInt(jPCadastroAutor.jtfCodigo.getText()));
                    autor.setNomAutor(jPCadastroAutor.jtfNome.getText());
                    if(autor.getCodAutor() == null){
                        em.persist(autor);
                    }else{
                        em.merge(autor);
                    }
                    em.getTransaction().commit();
                    Messages.getInfoMessage("salvarSucesso", "do autor");
                } catch (Exception e) {
                    if (em != null) {
                        em.getTransaction().rollback();
                    }
                    Messages.getErrorMessage("salvarErro", "do autor", Messages.tratarMsg(e.getMessage()));
                } finally {
                    if (emf != null) {
                        emf.close();
                    }
                }
            }
        });
        
        botoes.jbFechar.addActionListener(new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent ae) {
                dispose();
            }
        });
        
        jPCadastroAutor.jbConsultaAutor.addActionListener(new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent ae) {
                getPrincipal().addItem(new JIFConsultaAutor(JIFAutor.this));
                
            }
        });
        
        botoes.jbLimpar.addActionListener(new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent ae) {
                new WindowUtil().limpar(JIFAutor.this);
            }
        });
    }
    
    
    private JFPrincipal getPrincipal(){
        return principal;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPCadastroAutor = new unibaveopencode.gui.panel.screens.JPCadastroAutor();

        setClosable(true);
        setIconifiable(true);
        setTitle("UnibaveOpenCode");
        getContentPane().add(jPCadastroAutor, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public unibaveopencode.gui.panel.screens.JPCadastroAutor jPCadastroAutor;
    // End of variables declaration//GEN-END:variables
}
