/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package unibaveopencode.gui.iframe.screens;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.MessageFormat;
import javax.persistence.EntityManager;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;
import unibaveopencode.gui.panel.components.buttons.JPBotaoCadastro;
import unibaveopencode.util.Messages;
import unibaveopencode.model.vo.LivroVO;

/**
 *
 * @author Stéfani
 */
public class JIFCadastroLivro extends javax.swing.JInternalFrame {

    /**
     * Creates new form JIFLivro
     */
    public JIFCadastroLivro() {
        initComponents();
        initBotoes();
    }

    public void initBotoes() {
        JPBotaoCadastro botoes = jPCadastroLivro.jPbotaoCadastro;
        botoes.jbSalvar.addActionListener(new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent ae) {
                EntityManagerFactory emf = null;
                EntityManager em = null;

                try {
                    emf = Persistence.createEntityManagerFactory("uocPU");
                    emf.createEntityManager();
                    em.getTransaction().begin();
                    LivroVO livro = new LivroVO();
                    livro.setNumTombo(Integer.getInteger(jPCadastroLivro.jtfNumTombo.getText()));
                    livro.setNomTitulo(jPCadastroLivro.jtfTitulo.getText());
                    livro.setDesAno(Integer.getInteger(jPCadastroLivro.jtfAno.getText()));
                    //AUTOR
                    //EDITORA
                    //CLASSIFICACÃO
                    livro.setDesUrl(jPCadastroLivro.jtfUrl.getText());
                    em.persist(livro);
                    em.getTransaction().commit();
                    Messages.getInfoMessage("salvarSucesso", "do livro");
                } catch (Exception e) {
                    if (em != null) {
                        em.getTransaction().rollback();
                    }
                    Messages.getErrorMessage("salvarErro", "do livro", Messages.tratarMsg(e.getMessage()));
                } finally {
                    if (emf != null) {
                        emf.close();
                    }
                }
            }
        });
        
        botoes.jbFechar.addActionListener(new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent ae) {
                dispose();
            }
        });

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPCadastroLivro = new unibaveopencode.gui.panel.screens.JPCadastroLivro();

        setClosable(true);
        setIconifiable(true);
        setTitle("UnibaveOpenCode");
        getContentPane().add(jPCadastroLivro, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private unibaveopencode.gui.panel.screens.JPCadastroLivro jPCadastroLivro;
    // End of variables declaration//GEN-END:variables
}
