/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package unibaveopencode.gui.iframe.screens;

/**
 *
 * @author Stéfani
 */
public class JIFImprimeQrCode extends javax.swing.JInternalFrame {

    /**
     * Creates new form JIFImprimeQrCode
     */
    public JIFImprimeQrCode() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPImprimeQrCode1 = new unibaveopencode.gui.panel.screens.JPImprimeQrCode();

        setClosable(true);
        setIconifiable(true);
        setTitle("UnibaveOpenCode");
        getContentPane().add(jPImprimeQrCode1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private unibaveopencode.gui.panel.screens.JPImprimeQrCode jPImprimeQrCode1;
    // End of variables declaration//GEN-END:variables
}
